# Generated by Django 5.0.6 on 2024-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateField()),
                ('expires_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('qualication', models.CharField(max_length=100)),
                ('profile_pic', models.TextField()),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('desciption', models.TextField()),
                ('time_stamp', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
