# Generated by Django 4.2.7 on 2024-07-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0002_otps_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otps',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
