# Generated by Django 4.2.7 on 2024-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_delete_otps_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('qualication', models.CharField(max_length=100)),
                ('profile_pic', models.TextField()),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('desciption', models.TextField()),
                ('time_stamp', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(blank=True, choices=[('BEGINNER', 'begineer'), ('INTERMEDIATE', 'intermediate'), ('EXPERT', 'expert')], max_length=50)),
                ('tech', models.CharField(blank=True, choices=[('FRONTEND', 'frontend'), ('BACKEND', 'backend'), ('MOBILEAPP', 'mobileapp'), ('DATA SCIENCE', 'datascience'), ('ARTIFICIAL INTELLIGENCE/MACHINE LEARNING', 'ai/ml'), ('GAME DEVELOPMENT', 'gamedev')], max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
