# Generated by Django 4.2.7 on 2024-07-26 22:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_users_main_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('keys', models.TextField()),
                ('usage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 26, 23, 25, 41, 983349, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
