# Generated by Django 5.0.6 on 2024-07-27 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0005_resetpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_main',
            old_name='qualication',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 1, 9, 58, 801438, tzinfo=datetime.timezone.utc)),
        ),
    ]
