# Generated by Django 5.0.6 on 2024-07-27 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0006_rename_qualication_users_main_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 3, 30, 59, 647629, tzinfo=datetime.timezone.utc)),
        ),
    ]
