# Generated by Django 5.0.2 on 2024-07-27 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0006_rename_qualication_users_main_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_main',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 2, 0, 15, 175406, tzinfo=datetime.timezone.utc)),
        ),
    ]
