# Generated by Django 5.0.2 on 2024-07-27 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_rename_desciption_users_main_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 2, 5, 43, 345367, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
