# Generated by Django 5.0.2 on 2024-07-27 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_alter_resetpass_expires_at_alter_users_main_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 2, 7, 36, 558759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'begineer'), ('INTERMEDIATE', 'intermediate'), ('EXPERT', 'expert')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_main',
            name='tech',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'frontend'), ('BACKEND', 'backend'), ('MOBILEAPP', 'mobileapp'), ('DATA SCIENCE', 'datascience'), ('ARTIFICIAL INTELLIGENCE/MACHINE LEARNING', 'ai/ml'), ('GAME DEVELOPMENT', 'gamedev')], max_length=150, null=True),
        ),
    ]
