# Generated by Django 5.0.6 on 2024-07-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_alter_resetpass_expires_at'),
        ('auth1', '0009_alter_resetpass_expires_at_alter_users_main_level_and_more'),
    ]

    operations = [
    ]
