# Generated by Django 5.0.6 on 2024-07-27 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0010_merge_20240727_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 3, 45, 24, 740137, tzinfo=datetime.timezone.utc)),
        ),
    ]
