# Generated by Django 4.2.7 on 2024-07-27 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0011_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_main',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 8, 35, 23, 113926, tzinfo=datetime.timezone.utc)),
        ),
    ]
