# Generated by Django 4.2.7 on 2024-07-27 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0012_users_main_experience_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 8, 37, 25, 676763, tzinfo=datetime.timezone.utc)),
        ),
    ]
