# Generated by Django 4.2.7 on 2024-07-27 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0013_alter_resetpass_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_main',
            name='experience',
        ),
        migrations.AlterField(
            model_name='resetpass',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 8, 41, 32, 892896, tzinfo=datetime.timezone.utc)),
        ),
    ]
