# Generated by Django 4.2.7 on 2024-07-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth1', '0004_users_main_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('group_id', models.CharField(default=None, max_length=150, null=True)),
                ('timestamp', models.DateField(default=None, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=150, null=True)),
                ('username', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.joined')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Chatgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default=None, max_length=150, null=True)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('users_online', models.ManyToManyField(blank=True, related_name='online_in_groups', to='auth1.users_main')),
            ],
        ),
    ]
