# Generated by Django 4.2.7 on 2024-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(blank=True, max_length=100)),
                ('option2', models.CharField(blank=True, max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('ans', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('BEGINNER', 'begineer'), ('INTERMEDIATE', 'intermediate'), ('EXPERT', 'expert')], max_length=50)),
                ('tech', models.CharField(blank=True, choices=[('FRONTEND', 'frontend'), ('BACKEND', 'backend'), ('MOBILEAPP', 'mobileapp'), ('DATA SCIENCE', 'datascience'), ('ARTIFICIAL INTELLIGENCE/MACHINE LEARNING', 'ai/ml'), ('GAME DEVELOPMENT', 'gamedev')], max_length=150)),
            ],
        ),
    ]
