# Generated by Django 5.0.6 on 2024-07-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tech',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'frontend'), ('BACKEND', 'backend'), ('MOBILEAPP', 'mobileapp'), ('DATA SCIENCE', 'datascience'), ('ARTIFICIAL INTELLIGENCE/MACHINE LEARNING', 'ai/ml'), ('GAME DEVELOPMENT', 'gamedev')], max_length=150, null=True),
        ),
    ]
